### ISSUE TITLE
Add more detail about IESOs on home page

### ISSUE THREAD

**Issue by vvcb** [vvcb/vvcb.github.io#6]
Edit the text on the home page to include the following text. Remove this text from the 'About.md' file. Doesn't have to be on both pages.

_Integrated Emergency Surgical Officers are advanced associate clinicians who have completed a graduate degree (MSc) in integrated emergency general surgery, obstetrics and gynaecology (IEGSOG curriculum, 2009). Further information on the eligibility criteria and the curriculum are available on the website of Mekelle University of Health Sciences.

IESOs are responsible for the diagnosis and management of emergency general surgical, obstetric and gynaecological emergencies as well as truama in resource-constrained health centres. Since they started a few years ago, they have been responsible for saving a huge number of lives and improving the mortality and morbidity associated with a child-birth as well other surgical emergencies.

Their role is not only limited to clinical activities but may also extend to include research, teaching, management and leadership roles. This website will provide regular updates on the evolution of the role of IESOs in Ethiopia as well as their impact on the health of the people they serve._

**Comment by vvcb** [comment]
Once you have done this, commit and push to github. Work on your branch and not the master branch.

**Comment by iv2016** [comment]
Completed

**Comment by vvcb** [comment]
Well done on completing this so quickly.
